База знаний "TAdviser"
savushkin-r-d/T1-PLCnext-Demo-OSTIS pull request #4
Opened 2023-12-13 12:30 UTC by Bidway

2023-12-26 08:20 UTC, idzm commented
@ShunkevichDV - нужна твоя рецензия.

2024-01-29 19:17 UTC, ShunkevichDV requested changes

2024-01-29 19:17 UTC, ShunkevichDV commented on about_auto/concept_answer_about_confection_phrase.gwf
> +<GWF version="2.0">
GWF-файлы создаются в специальном редакторе KBE (https://github.com/ostis-ai/kbe) и являются исходниками для scg-текстов. Их нельзя редактировать обычным текстовым редактором, такой файл потом не соберется сборщиком базы знаний

2024-01-29 19:17 UTC, ShunkevichDV commented on about_auto/concept_answer_about_auto.scs
> +    ...;
Есть синтаксические ошибки, лучше всего проверять scs-файлы сборщиком, входящим состав ostis-платформы (https://github.com/ostis-ai/sc-machine) и потом смотреть, что отображается в системе, все ли так, как мы хотели.

2024-01-29 19:21 UTC, ShunkevichDV requested changes
В целом неплохая попытка сделать фрагмент базы знаний, похожий на OSTIS, но теперь нужно разобраться с соответствующими инструментами

2024-04-16 05:59 UTC, closed without merging